Setting up edeliver

diff --git a/.deliver/config b/.deliver/config
--- a/.deliver/config
+++ b/.deliver/config
@@ -1,23 +1,26 @@
 APP="vegsochk_umbrella"
 
-BUILD_HOST="159.65.14.195"
-BUILD_USER="builder"
+BUILD_HOST="139.59.121.93"
+BUILD_USER="deploy"
 BUILD_AT="/home/$BUILD_USER/edeliver/$APP/builds"
 
 RELEASE_DIR="$BUILD_AT/apps/$APP/rel/$APP"
 
-STAGING_HOSTS="159.65.14.195"
-STAGING_USER="deployer"
-TEST_AT="/home/elixir_deployer/$APP_staging"
+# prevent re-installing node modules; this defaults to "."
+GIT_CLEAN_PATHS="_build rel priv/static"
+
+STAGING_HOSTS="139.59.121.93"
+STAGING_USER="deploy"
+TEST_AT="/home/$BUILD_USER/staging"
 
 
-PRODUCTION_HOSTS="159.65.14.195" # deploy / production hosts separated by space # 54.163.178.252
-PRODUCTION_USER="deployer" # local user at deploy hosts
-DELIVER_TO="/home/elixir_deployer/$APP_staging" # deploy directory on production hosts
+PRODUCTION_HOSTS="139.59.121.93" # deploy / production hosts separated by space # 54.163.178.252
+PRODUCTION_USER="deploy" # local user at deploy hosts
+DELIVER_TO="/home/$BUILD_USER" # deploy directory on production hosts
 
 # For *Phoenix* projects, symlink prod.secret.exs to our tmp source
 pre_erlang_get_and_update_deps() {
-  local _prod_secret_path="/home/builder/prod.secret.exs"
+  local _prod_secret_path="/home/deploy/prod.secret.exs"
   if [ "$TARGET_MIX_ENV" = "prod" ]; then
     __sync_remote "
       ln -sfn '$_prod_secret_path' '$BUILD_AT/apps/vegsochk/config/prod.secret.exs'
@@ -26,4 +29,23 @@ pre_erlang_get_and_update_deps() {
       ln -sfn '$_prod_secret_path' '$BUILD_AT/apps/vegsochk_web/config/prod.secret.exs'
     "
   fi
+}
+
+pre_erlang_clean_compile() {
+  status "Running phoenix.digest" # log output prepended with "----->"
+  __sync_remote " # runs the commands on the build host
+    # [ -f ~/.profile ] && source ~/.profile # load profile (optional)
+    source ~/.profile
+    # echo \$PATH # check if rbenv is in the path
+    set -e # fail if any command fails (recommended)
+    cd '$BUILD_AT' # enter the build directory on the build host (required)
+    # prepare something
+    mkdir -p priv/static # required by the phoenix.digest task
+    npm install 
+
+    ./node_modules/brunch/bin/brunch build --production 
+
+    # run your custom task
+    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phoenix.digest $SILENCE
+  "
 }
